# -*- coding: utf-8 -*-
"""inventory_optimization_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNURHLuZDJk4gsGl9WzWuTMcbdDNMjdw
"""

!pip install pandas prophet scipy streamlit

import pandas as pd
from prophet import Prophet
import matplotlib.pyplot as plt
from scipy.optimize import linprog
import streamlit as st

df = pd.read_csv("inventory_sales_data.csv")
df['date'] = pd.to_datetime(df['date'])

sku_df = df[df['sku'] == 'SKU_001'][['date', 'sales']].rename(columns={'date': 'ds', 'sales': 'y'})

model = Prophet()
model.fit(sku_df)
future = model.make_future_dataframe(periods=30)
forecast = model.predict(future)

holding_cost_per_unit = 0.5
ordering_cost = 100

daily_demand = forecast.tail(30)['yhat'].values
x = [1] * len(daily_demand)

c = [holding_cost_per_unit * d + ordering_cost for d in daily_demand]
bounds = [(0, None) for _ in x]

res = linprog(c, bounds=bounds, method='highs')

st.title("📦 Inventory Optimization Dashboard")
st.subheader("📊 Forecasted Demand for Next 30 Days")
st.line_chart(forecast.set_index('ds')['yhat'].tail(30))

st.subheader("🔧 Optimized Inventory Order Plan")
if res.success:
    st.write("Total Estimated Cost: ₹", round(res.fun, 2))
    st.bar_chart(res.x)
else:
    st.error("Optimization Failed.")